//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by color_loupe.rc
//
#define IDR_MENU_CXT                    101
#define IDS_TOAST_SCALE_FORMAT          102
#define IDS_TOAST_FOLLOW_CURSOR_ON      103
#define IDS_TOAST_FOLLOW_CURSOR_OFF     104
#define IDS_TOAST_CLIPBOARD             105
#define IDS_TOAST_GRID_ON               106
#define IDS_TOAST_GRID_OFF              107
#define IDS_CMD_NONE                    108
#define IDS_CMD_SWAP_ZOOM               109
#define IDS_CMD_COPY_COLOR              110
#define IDS_CMD_FOLLOW_CURSOR           111
#define IDS_CMD_CENTRALIZE              112
#define IDS_CMD_TOGGLE_GRID             113
#define IDS_CMD_ZOOM_STEP_DOWN          114
#define IDS_CMD_ZOOM_STEP_UP            115
#define IDS_CMD_CXT_MENU                116
#define IDS_CMD_OPTIONS_DLG             117
#define IDS_MOUSEBUTTON_NONE            118
#define IDS_MOUSEBUTTON_LEFT            119
#define IDS_MOUSEBUTTON_RIGHT           120
#define IDS_MOUSEBUTTON_MIDDLE          121
#define IDS_MOUSEBUTTON_X1              122
#define IDS_MOUSEBUTTON_X2              123
#define IDS_MODKEY_COND_NONE            124
#define IDS_MODKEY_COND_ON              125
#define IDS_MODKEY_COND_OFF             126
#define IDS_MODKEY_FAKE_FLAT            127
#define IDS_MODKEY_FAKE_ON              128
#define IDS_MODKEY_FAKE_OFF             129
#define IDS_MODKEY_FAKE_INV             130
#define IDS_ZOOM_PIVOT_CENTER           131
#define IDS_ZOOM_PIVOT_CURSOR           132
#define IDS_RAILMODE_NONE               133
#define IDS_RAILMODE_CROSS              134
#define IDS_RAILMODE_OCTAGONAL          135
#define IDS_TIPMODE_FRAIL               136
#define IDS_TIPMODE_STATIONARY          137
#define IDS_TIPMODE_STICKY              138
#define IDS_SCALE_FORMAT_FRAC           139
#define IDS_SCALE_FORMAT_DEC            140
#define IDS_SCALE_FORMAT_PCT            141
#define IDS_DLG_TAB_ZOOM_WHEEL          142
#define IDS_DLG_TAB_DRAG_LOUPE          143
#define IDS_DLG_TAB_DRAG_TIP            144
#define IDS_DLG_TAB_DRAG_EXEDIT         145
#define IDS_DLG_TAB_CLK_LEFT            146
#define IDS_DLG_TAB_CLK_RIGHT           147
#define IDS_DLG_TAB_CLK_MIDDLE          148
#define IDS_DLG_TAB_CLK_X1              149
#define IDS_DLG_TAB_CLK_X2              150
#define IDS_DLG_TAB_CMD_OPTIONS         151
#define IDS_DLG_TAB_TOAST               152
#define IDS_DLG_TAB_GRID                153
#define IDS_DESC_DRAG_KEYCOND           154
#define IDS_DESC_DRAG_RANGE             155
#define IDS_DESC_ZOOM_STEPS             156
#define IDS_DESC_TIP_FRAIL              157
#define IDS_DESC_TIP_STATIONARY         158
#define IDS_DESC_TIP_STICKY             159
#define IDS_DESC_EXEDIT_FAKE            160
#define IDS_DESC_GRID_KINDS             161
#define IDD_VSCROLLFORM                 800
#define IDD_SETTINGS                    801
#define IDD_SETTINGS_FORM_CLICK_ACTION  802
#define IDD_SETTINGS_FORM_DRAG_KEYS     803
#define IDD_SETTINGS_FORM_DRAG_RANGE    804
#define IDD_SETTINGS_FORM_WHEEL_ZOOM    805
#define IDD_SETTINGS_FORM_DRAG_LOUPE    806
#define IDD_SETTINGS_FORM_DRAG_TIP      807
#define IDD_SETTINGS_FORM_DRAG_EXEDIT   808
#define IDD_SETTINGS_FORM_ZOOM          809
#define IDD_SETTINGS_FORM_TOAST         810
#define IDD_SETTINGS_FORM_GRID          811
#define IDD_SETTINGS_FORM_CMD_SWAP      812
#define IDD_SETTINGS_FORM_CMD_ZOOM_STEP 813
#define IDC_LIST1                       1001
#define IDC_COMBO1                      1002
#define IDC_COMBO2                      1003
#define IDC_COMBO3                      1004
#define IDC_COMBO4                      1005
#define IDC_EDIT1                       1006
#define IDC_EDIT2                       1007
#define IDC_EDIT3                       1008
#define IDC_SPIN1                       1009
#define IDC_SPIN2                       1010
#define IDC_CHECK1                      1011
#define IDC_CHECK2                      1012
#define IDC_CHECK3                      1013
#define IDC_CHECK4                      1014
#define IDC_RADIO1                      1015
#define IDC_RADIO2                      1016
#define IDC_RADIO3                      1017
#define IDC_RADIO4                      1018
#define IDC_RADIO5                      1019
#define IDC_RADIO6                      1020
#define IDC_RADIO7                      1021
#define IDC_RADIO8                      1022
#define IDC_RADIO9                      1023
#define IDC_SLIDER1                     1024
#define IDC_SLIDER2                     1025
#define IDM_CXT_FOLLOW_CURSOR           40001
#define IDM_CXT_SHOW_GRID               40002
#define IDM_CXT_SWAP_ZOOM               40003
#define IDM_CXT_CENTRALIZE              40004
#define IDM_CXT_PT_COPY_COLOR           40005
#define IDM_CXT_PT_MOVE_CENTER          40006
#define IDM_CXT_PT_COPY_COORD_TL        40007
#define IDM_CXT_PT_COPY_COORD_C         40008
#define IDM_CXT_TIP_MODE_FRAIL          40009
#define IDM_CXT_TIP_MODE_STATIONARY     40010
#define IDM_CXT_TIP_MODE_STICKY         40011
#define IDM_CXT_REVERSE_WHEEL           40012
#define IDM_CXT_SETTINGS                40013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        814
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
