//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by color_loupe.rc
//
#define IDR_MENU_CXT                    101
#define IDS_TOAST_SCALE_FORMAT          102
#define IDS_TOAST_FOLLOW_CURSOR_ON      103
#define IDS_TOAST_FOLLOW_CURSOR_OFF     104
#define IDS_TOAST_CLIPBOARD             105
#define IDS_TOAST_GRID_ON               106
#define IDS_TOAST_GRID_OFF              107
#define IDS_CMD_NONE                    108
#define IDS_CMD_SWAP_ZOOM               109
#define IDS_CMD_COPY_COLOR              110
#define IDS_CMD_COPY_COORD              111
#define IDS_CMD_FOLLOW_CURSOR           112
#define IDS_CMD_CENTRALIZE              113
#define IDS_CMD_TOGGLE_GRID             114
#define IDS_CMD_ZOOM_STEP_DOWN          115
#define IDS_CMD_ZOOM_STEP_UP            116
#define IDS_CMD_BRING_CENTER            117
#define IDS_CMD_CXT_MENU                118
#define IDS_CMD_OPTIONS_DLG             119
#define IDS_MOUSEBUTTON_NONE            120
#define IDS_MOUSEBUTTON_LEFT            121
#define IDS_MOUSEBUTTON_RIGHT           122
#define IDS_MOUSEBUTTON_MIDDLE          123
#define IDS_MOUSEBUTTON_X1              124
#define IDS_MOUSEBUTTON_X2              125
#define IDS_MODKEY_COND_NONE            126
#define IDS_MODKEY_COND_ON              127
#define IDS_MODKEY_COND_OFF             128
#define IDS_MODKEY_FAKE_FLAT            129
#define IDS_MODKEY_FAKE_ON              130
#define IDS_MODKEY_FAKE_OFF             131
#define IDS_MODKEY_FAKE_INV             132
#define IDS_ZOOM_PIVOT_CENTER           133
#define IDS_ZOOM_PIVOT_CURSOR           134
#define IDS_ZOOM_PIVOT_START_PT         135
#define IDS_RAILMODE_NONE               136
#define IDS_RAILMODE_CROSS              137
#define IDS_RAILMODE_OCTAGONAL          138
#define IDS_TIPMODE_FRAIL               139
#define IDS_TIPMODE_STATIONARY          140
#define IDS_TIPMODE_STICKY              141
#define IDS_TIP_COLOR_FMT_HEX           142
#define IDS_TIP_COLOR_FMT_RGB           143
#define IDS_CXT_COLOR_FMT_HEX           144
#define IDS_CXT_COLOR_FMT_RGB           145
#define IDS_COORD_FMT_TOPLEFT           146
#define IDS_COORD_FMT_CENTER            147
#define IDS_SCALE_FORMAT_FRAC           148
#define IDS_SCALE_FORMAT_DEC            149
#define IDS_SCALE_FORMAT_PCT            150
#define IDS_DLG_TAB_ZOOM_WHEEL          151
#define IDS_DLG_TAB_DRAG_LOUPE          152
#define IDS_DLG_TAB_DRAG_TIP            153
#define IDS_DLG_TAB_DRAG_ZOOM           154
#define IDS_DLG_TAB_DRAG_EXEDIT         155
#define IDS_DLG_TAB_CLK_LEFT            156
#define IDS_DLG_TAB_CLK_RIGHT           157
#define IDS_DLG_TAB_CLK_MIDDLE          158
#define IDS_DLG_TAB_CLK_X1              159
#define IDS_DLG_TAB_CLK_X2              160
#define IDS_DLG_TAB_CMD_OPTIONS         161
#define IDS_DLG_TAB_TOAST               162
#define IDS_DLG_TAB_GRID                163
#define IDS_DLG_TAB_COLOR               164
#define IDS_DLG_TAB_SEPARATOR           165
#define IDS_DESC_DRAG_KEYCOND           166
#define IDS_DESC_DRAG_RANGE             167
#define IDS_DESC_ZOOM_STEPS             168
#define IDS_DESC_TIP_FRAIL              169
#define IDS_DESC_TIP_STATIONARY         170
#define IDS_DESC_TIP_STICKY             171
#define IDS_DESC_DRAG_ZOOM              172
#define IDS_DESC_EXEDIT_FAKE            173
#define IDS_DESC_GRID_KINDS             174
#define IDS_DESC_CLIPBOARD_FMT          175
#define IDS_DESC_CMD_NONE               176
#define IDS_DESC_CMD_SWAP_ZOOM          177
#define IDS_DESC_CMD_COPY_COLOR         178
#define IDS_DESC_CMD_COPY_COORD         179
#define IDS_DESC_CMD_FOLLOW             180
#define IDS_DESC_CMD_CENTRALIZE         181
#define IDS_DESC_CMD_GRID               182
#define IDS_DESC_CMD_ZOOM_UP            183
#define IDS_DESC_CMD_ZOOM_DOWN          184
#define IDS_DESC_CMD_BRING_CENTER       185
#define IDS_DESC_CMD_CXT_MENU           186
#define IDS_DESC_CMD_SETTINGS           187
#define IDS_DLG_TOAST_SAMPLE            188
#define IDS_COLOR_THEME_LIGHT           189
#define IDS_COLOR_THEME_DARK            190
#define IDD_VSCROLLFORM                 800
#define IDD_SETTINGS                    801
#define IDD_SETTINGS_FORM_CLICK_ACTION  802
#define IDD_SETTINGS_FORM_DRAG_KEYS     803
#define IDD_SETTINGS_FORM_DRAG_RANGE    804
#define IDD_SETTINGS_FORM_WHEEL_ZOOM    805
#define IDD_SETTINGS_FORM_DRAG_LOUPE    806
#define IDD_SETTINGS_FORM_DRAG_TIP      807
#define IDD_SETTINGS_FORM_DRAG_TIP_FMT  808
#define IDD_SETTINGS_FORM_TIP_METRICS   809
#define IDD_SETTINGS_FORM_DRAG_ZOOM     810
#define IDD_SETTINGS_FORM_DRAG_EXEDIT   811
#define IDD_SETTINGS_FORM_ZOOM          812
#define IDD_SETTINGS_FORM_TOAST         813
#define IDD_SETTINGS_FORM_TOAST_METRICS 814
#define IDD_SETTINGS_FORM_GRID          815
#define IDD_SETTINGS_FORM_CMD_SWAP      816
#define IDD_SETTINGS_FORM_CMD_ZOOM_STEP 817
#define IDD_SETTINGS_FORM_CMD_CLIPBOARD 818
#define IDD_SETTINGS_FORM_CMD_DESC      819
#define IDD_SETTINGS_FORM_FONT          820
#define IDD_SETTINGS_FORM_COLOR         821
#define IDC_LIST1                       1001
#define IDC_COMBO1                      1002
#define IDC_COMBO2                      1003
#define IDC_COMBO3                      1004
#define IDC_COMBO4                      1005
#define IDC_EDIT1                       1006
#define IDC_EDIT2                       1007
#define IDC_EDIT3                       1008
#define IDC_EDIT4                       1009
#define IDC_EDIT5                       1010
#define IDC_EDIT6                       1011
#define IDC_EDIT7                       1012
#define IDC_EDIT8                       1013
#define IDC_SPIN1                       1014
#define IDC_SPIN2                       1015
#define IDC_SPIN3                       1016
#define IDC_SPIN4                       1017
#define IDC_SPIN5                       1018
#define IDC_SPIN6                       1019
#define IDC_SPIN7                       1020
#define IDC_SPIN8                       1021
#define IDC_CHECK1                      1022
#define IDC_CHECK2                      1023
#define IDC_CHECK3                      1024
#define IDC_CHECK4                      1025
#define IDC_RADIO1                      1026
#define IDC_RADIO2                      1027
#define IDC_RADIO3                      1028
#define IDC_RADIO4                      1029
#define IDC_RADIO5                      1030
#define IDC_RADIO6                      1031
#define IDC_RADIO7                      1032
#define IDC_RADIO8                      1033
#define IDC_RADIO9                      1034
#define IDC_SLIDER1                     1035
#define IDC_SLIDER2                     1036
#define IDC_RECT1                       1037
#define IDC_BUTTON1                     1038
#define IDC_BUTTON2                     1039
#define IDC_BUTTON3                     1040
#define IDC_BUTTON4                     1041
#define IDC_BUTTON5                     1042
#define IDC_BUTTON6                     1043
#define IDM_CXT_FOLLOW_CURSOR           40001
#define IDM_CXT_SHOW_GRID               40002
#define IDM_CXT_SWAP_ZOOM               40003
#define IDM_CXT_CENTRALIZE              40004
#define IDM_CXT_PT_COPY_COLOR           40005
#define IDM_CXT_PT_BRING_CENTER         40006
#define IDM_CXT_PT_COPY_COORD           40007
#define IDM_CXT_TIP_MODE_FRAIL          40008
#define IDM_CXT_TIP_MODE_STATIONARY     40009
#define IDM_CXT_TIP_MODE_STICKY         40010
#define IDM_CXT_REVERSE_WHEEL           40011
#define IDM_CXT_SETTINGS                40012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        822
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
