//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by color_loupe.rc
//
#define IDR_MENU_CXT                    101
#define IDS_TOAST_SCALE_FORMAT          103
#define IDS_TOAST_FOLLOW_CURSOR_ON      104
#define IDS_TOAST_FOLLOW_CURSOR_OFF     105
#define IDS_TOAST_CLIPBOARD             106
#define IDM_CXT_FOLLOW_CURSOR           40001
#define IDM_CXT_CENTRALIZE              40002
#define IDM_CXT_REVERSE_WHEEL           40003
#define IDM_CXT_PIVOT_CENTER            40004
#define IDM_CXT_PIVOT_MOUSE             40005
#define IDM_CXT_PIVOT_DRAG_CENTER       40006
#define IDM_CXT_PIVOT_DRAG_MOUSE        40007
#define IDM_CXT_LATTICE                 40008
#define IDM_CXT_RAIL_NONE               40009
#define IDM_CXT_RAIL_CROSS              40010
#define IDM_CXT_RAIL_OCTAGONAL          40011
#define IDM_CXT_TIP_MODE_NONE           40012
#define IDM_CXT_TIP_MODE_FRAIL          40013
#define IDM_CXT_TIP_MODE_STATIONARY     40014
#define IDM_CXT_TIP_MODE_STICKY         40015
#define IDM_CXT_TIP_RAIL_NONE           40016
#define IDM_CXT_TIP_RAIL_CROSS          40017
#define IDM_CXT_TIP_RAIL_OCTAGONAL      40018
#define IDM_CXT_TOAST_NOTIFY_SCALE      40019
#define IDM_CXT_TOAST_NOTIFY_FOLLOW_CURSOR 40020
#define IDM_CXT_TOAST_NOTIFY_CLIPBOARD  40021
#define IDM_CXT_TOAST_PLACEMENT_CENTER  40022
#define IDM_CXT_TOAST_PLACEMENT_LEFT_TOP 40023
#define IDM_CXT_TOAST_PLACEMENT_RIGHT_TOP 40024
#define IDM_CXT_TOAST_PLACEMENT_RIGHT_BOTTOM 40025
#define IDM_CXT_TOAST_PLACEMENT_LEFT_BOTTOM 40026
#define IDM_CXT_TOAST_SCALE_FMT_FRAC    40027
#define IDM_CXT_TOAST_SCALE_FMT_DEC     40028
#define IDM_CXT_TOAST_SCALE_FMT_PCT     40029
#define IDM_CXT_PIVOT_SWAP_CENTER       40030
#define IDM_CXT_PIVOT_SWAP_MOUSE        40031
#define IDM_CXT_COMMAND_LDBLCLK_NONE    40032
#define IDM_CXT_COMMAND_LDBLCLK_FOLLOW_CURSOR 40033
#define IDM_CXT_COMMAND_LDBLCLK_SWAP_ZOOM 40034
#define IDM_CXT_COMMAND_LDBLCLK_CENTRALIZE 40035
#define IDM_CXT_COMMAND_LDBLCLK_COPY_COLOR 40036
#define IDM_CXT_COMMAND_LDBLCLK_MENU    40037
#define IDM_CXT_COMMAND_RDBLCLK_NONE    40038
#define IDM_CXT_COMMAND_RDBLCLK_FOLLOW_CURSOR 40039
#define IDM_CXT_COMMAND_RDBLCLK_SWAP_ZOOM 40040
#define IDM_CXT_COMMAND_RDBLCLK_CENTRALIZE 40041
#define IDM_CXT_COMMAND_RDBLCLK_COPY_COLOR 40042
#define IDM_CXT_COMMAND_RDBLCLK_MENU    40043
#define IDM_CXT_COMMAND_MCLICK_NONE     40044
#define IDM_CXT_COMMAND_MCLICK_FOLLOW_CURSOR 40045
#define IDM_CXT_COMMAND_MCLICK_SWAP_ZOOM 40046
#define IDM_CXT_COMMAND_MCLICK_CENTRALIZE 40047
#define IDM_CXT_COMMAND_MCLICK_COPY_COLOR 40048
#define IDM_CXT_COMMAND_MCLICK_MENU     40049

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40050
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
